# Generated by Django 5.1 on 2026-04-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_clerk_id_user_clerk_user_id_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='workspaces.workspace'),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='clerk_user_id',
            new_name='clerk_id',
        ),
    ]
