# Generated by Django 5.1 on 2026-03-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_chatsession_reminder_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='assessment.userprofile'),
        ),
    ]
