# Generated by Django 5.1 on 2026-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessmentresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin')], default='teacher', max_length=20),
        ),
    ]
