# Generated by Django 5.1 on 2026-03-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_clerk_id_alter_user_google_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
